figure(1)
plot(mse_vec1)
title('MSE path w/feature 3')
legend('Class 1')
figure(2)
plot(mse_vec2)
title('MSE path w/feature 3')
legend('Class 2')
figure(3)
plot(mse_vec3)
title('MSE path w/feature 3')
legend('Class 3')
